// <auto-generated />
using System;
using EfcCodeFirst.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfcCodeFirst.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260509132604_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EfcCodeFirst.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("RateType")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Rate_Type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("Contracts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProjectId = 4,
                            RateType = "Hourly"
                        },
                        new
                        {
                            Id = 2,
                            ProjectId = 1,
                            RateType = "Fixed"
                        },
                        new
                        {
                            Id = 3,
                            ProjectId = 3,
                            RateType = "Fixed"
                        },
                        new
                        {
                            Id = 4,
                            ProjectId = 2,
                            RateType = "Hourly"
                        },
                        new
                        {
                            Id = 5,
                            ProjectId = 5,
                            RateType = "Hourly"
                        });
                });

            modelBuilder.Entity("EfcCodeFirst.Entites.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("Clients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Email1",
                            Name = "Name1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Email2",
                            Name = "Name2"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Email3",
                            Name = "Name3"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Email4",
                            Name = "Name4"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Email5",
                            Name = "Name5"
                        });
                });

            modelBuilder.Entity("EfcCodeFirst.Entites.Freelancer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Freelancer")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("Freelancers", (string)null);

                    b.HasDiscriminator<string>("Freelancer").HasValue("Freelancer");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EfcCodeFirst.Entites.FreelancerSkill", b =>
                {
                    b.Property<int>("FreelancerId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Proficiency")
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("FreelancerId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("FreelancerSkills", (string)null);

                    b.HasData(
                        new
                        {
                            FreelancerId = 1,
                            SkillId = 1,
                            Proficiency = "Expert"
                        },
                        new
                        {
                            FreelancerId = 1,
                            SkillId = 2,
                            Proficiency = "Advanced"
                        },
                        new
                        {
                            FreelancerId = 2,
                            SkillId = 3,
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            FreelancerId = 3,
                            SkillId = 4,
                            Proficiency = "Expert"
                        },
                        new
                        {
                            FreelancerId = 4,
                            SkillId = 5,
                            Proficiency = "Beginner"
                        },
                        new
                        {
                            FreelancerId = 5,
                            SkillId = 6,
                            Proficiency = "Advanced"
                        },
                        new
                        {
                            FreelancerId = 6,
                            SkillId = 7,
                            Proficiency = "Intermediate"
                        });
                });

            modelBuilder.Entity("EfcCodeFirst.Entites.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ProjectId");

                    b.ToTable("Invoices", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            ProjectId = 3,
                            Status = "Draft"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            ProjectId = 1,
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            ProjectId = 5,
                            Status = "Overdue"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            ProjectId = 4,
                            Status = "Sent"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            ProjectId = 2,
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            ProjectId = 1,
                            Status = "Draft"
                        });
                });

            modelBuilder.Entity("EfcCodeFirst.Entites.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Projects", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 3,
                            IsDeleted = false,
                            Status = "Draft",
                            Title = "Title1"
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 5,
                            IsDeleted = false,
                            Status = "Overdue",
                            Title = "Title2"
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 4,
                            IsDeleted = false,
                            Status = "Sent",
                            Title = "Title3"
                        },
                        new
                        {
                            Id = 4,
                            ClientId = 1,
                            IsDeleted = false,
                            Status = "Overdue",
                            Title = "Title4"
                        },
                        new
                        {
                            Id = 5,
                            ClientId = 2,
                            IsDeleted = false,
                            Status = "Paid",
                            Title = "Title5"
                        });
                });

            modelBuilder.Entity("EfcCodeFirst.Entites.ProjectFreelancer", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("FreelancerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("HoursAllocated")
                        .HasColumnType("int")
                        .HasColumnName("Hours_Allocated");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("ProjectId", "FreelancerId");

                    b.HasIndex("FreelancerId");

                    b.ToTable("ProjectFreelancer", (string)null);

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            FreelancerId = 1,
                            HoursAllocated = 40,
                            Role = "Developer"
                        },
                        new
                        {
                            ProjectId = 1,
                            FreelancerId = 2,
                            HoursAllocated = 20,
                            Role = "Project_Management"
                        },
                        new
                        {
                            ProjectId = 2,
                            FreelancerId = 3,
                            HoursAllocated = 35,
                            Role = "Designer"
                        },
                        new
                        {
                            ProjectId = 3,
                            FreelancerId = 4,
                            HoursAllocated = 15,
                            Role = "Developer"
                        },
                        new
                        {
                            ProjectId = 3,
                            FreelancerId = 1,
                            HoursAllocated = 10,
                            Role = "Markting"
                        },
                        new
                        {
                            ProjectId = 4,
                            FreelancerId = 5,
                            HoursAllocated = 50,
                            Role = "Project_Management"
                        },
                        new
                        {
                            ProjectId = 5,
                            FreelancerId = 6,
                            HoursAllocated = 25,
                            Role = "Developer"
                        },
                        new
                        {
                            ProjectId = 5,
                            FreelancerId = 2,
                            HoursAllocated = 30,
                            Role = "Markting"
                        });
                });

            modelBuilder.Entity("EfcCodeFirst.Entites.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Skill_Name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("Skills", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SkillName = "C# Development"
                        },
                        new
                        {
                            Id = 2,
                            SkillName = "ASP.NET Core"
                        },
                        new
                        {
                            Id = 3,
                            SkillName = "React.js"
                        },
                        new
                        {
                            Id = 4,
                            SkillName = "SQL Server"
                        },
                        new
                        {
                            Id = 5,
                            SkillName = "UI/UX Design"
                        },
                        new
                        {
                            Id = 6,
                            SkillName = "DevOps"
                        },
                        new
                        {
                            Id = 7,
                            SkillName = "Project Management"
                        },
                        new
                        {
                            Id = 8,
                            SkillName = "Mobile App Development"
                        });
                });

            modelBuilder.Entity("EfcCodeFirst.Entites.AgencyFreelancer", b =>
                {
                    b.HasBaseType("EfcCodeFirst.Entites.Freelancer");

                    b.Property<string>("AgencyContactEmail")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Agency_Contact_Email");

                    b.Property<string>("AgencyName")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Agency_Name");

                    b.HasDiscriminator().HasValue("AGENCY");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Name = "Name2",
                            Type = "Type2",
                            AgencyContactEmail = "Email2",
                            AgencyName = "AgencyName2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Name3",
                            Type = "Type3",
                            AgencyContactEmail = "Email3",
                            AgencyName = "AgencyName3"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Name5",
                            Type = "Type5",
                            AgencyContactEmail = "Email5",
                            AgencyName = "AgencyName5"
                        });
                });

            modelBuilder.Entity("EfcCodeFirst.Entites.IndependentFreelancer", b =>
                {
                    b.HasBaseType("EfcCodeFirst.Entites.Freelancer");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("HourlyRate")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("INDEPENDENT");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Name1",
                            Type = "Type1",
                            Availability = "Full_Time",
                            HourlyRate = 50
                        },
                        new
                        {
                            Id = 4,
                            Name = "Name4",
                            Type = "Type4",
                            Availability = "Part_Time",
                            HourlyRate = 60
                        },
                        new
                        {
                            Id = 6,
                            Name = "Name6",
                            Type = "Type6",
                            Availability = "Full_Time",
                            HourlyRate = 70
                        });
                });

            modelBuilder.Entity("EfcCodeFirst.Contract", b =>
                {
                    b.HasOne("EfcCodeFirst.Entites.Project", "Project")
                        .WithOne("Contract")
                        .HasForeignKey("EfcCodeFirst.Contract", "ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("EfcCodeFirst.Entites.ValueObjects.MoneyAmount", "MoneyAmount", b1 =>
                        {
                            b1.Property<int>("ContractId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(15, 3)
                                .HasColumnType("decimal(15,3)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("VARCHAR");

                            b1.HasKey("ContractId");

                            b1.ToTable("Contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractId");

                            b1.HasData(
                                new
                                {
                                    ContractId = 1,
                                    Amount = 50.00m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ContractId = 2,
                                    Amount = 5000.00m,
                                    Currency = "EUR"
                                },
                                new
                                {
                                    ContractId = 3,
                                    Amount = 75.00m,
                                    Currency = "GBP"
                                },
                                new
                                {
                                    ContractId = 4,
                                    Amount = 1200.00m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ContractId = 5,
                                    Amount = 45.00m,
                                    Currency = "CAD"
                                });
                        });

                    b.Navigation("MoneyAmount")
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("EfcCodeFirst.Entites.Client", b =>
                {
                    b.OwnsOne("EfcCodeFirst.Entites.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<int>("ClientId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("VARCHAR");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("VARCHAR");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("VARCHAR");

                            b1.HasKey("ClientId");

                            b1.ToTable("Clients");

                            b1.WithOwner()
                                .HasForeignKey("ClientId");

                            b1.HasData(
                                new
                                {
                                    ClientId = 1,
                                    City = "City1",
                                    Country = "Country1",
                                    Street = "Street1"
                                },
                                new
                                {
                                    ClientId = 2,
                                    City = "City2",
                                    Country = "Country2",
                                    Street = "Street2"
                                },
                                new
                                {
                                    ClientId = 3,
                                    City = "City3",
                                    Country = "Country3",
                                    Street = "Street3"
                                },
                                new
                                {
                                    ClientId = 4,
                                    City = "City4",
                                    Country = "Country4",
                                    Street = "Street4"
                                },
                                new
                                {
                                    ClientId = 5,
                                    City = "City5",
                                    Country = "Country5",
                                    Street = "Street5"
                                });
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("EfcCodeFirst.Entites.Freelancer", b =>
                {
                    b.OwnsOne("EfcCodeFirst.Entites.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<int>("FreelancerId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("VARCHAR");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("VARCHAR");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("VARCHAR");

                            b1.HasKey("FreelancerId");

                            b1.ToTable("Freelancers");

                            b1.WithOwner()
                                .HasForeignKey("FreelancerId");

                            b1.HasData(
                                new
                                {
                                    FreelancerId = 1,
                                    City = "City1",
                                    Country = "Country1",
                                    Street = "Street1"
                                },
                                new
                                {
                                    FreelancerId = 2,
                                    City = "City2",
                                    Country = "Country2",
                                    Street = "Street2"
                                },
                                new
                                {
                                    FreelancerId = 3,
                                    City = "City3",
                                    Country = "Country3",
                                    Street = "Street3"
                                },
                                new
                                {
                                    FreelancerId = 4,
                                    City = "City4",
                                    Country = "Country4",
                                    Street = "Street4"
                                },
                                new
                                {
                                    FreelancerId = 5,
                                    City = "City5",
                                    Country = "Country5",
                                    Street = "Street5"
                                },
                                new
                                {
                                    FreelancerId = 6,
                                    City = "City6",
                                    Country = "Country6",
                                    Street = "Street6"
                                });
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("EfcCodeFirst.Entites.FreelancerSkill", b =>
                {
                    b.HasOne("EfcCodeFirst.Entites.Freelancer", "Freelancer")
                        .WithMany("FreelancerSkills")
                        .HasForeignKey("FreelancerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EfcCodeFirst.Entites.Skill", "Skill")
                        .WithMany("FreelancerSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Freelancer");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("EfcCodeFirst.Entites.Invoice", b =>
                {
                    b.HasOne("EfcCodeFirst.Entites.Project", "Project")
                        .WithMany("Invoices")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EfcCodeFirst.Entites.ValueObjects.MoneyAmount", "MoneyAmount", b1 =>
                        {
                            b1.Property<int>("InvoiceId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(15, 3)
                                .HasColumnType("decimal(15,3)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("VARCHAR");

                            b1.HasKey("InvoiceId");

                            b1.ToTable("Invoices");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceId");

                            b1.HasData(
                                new
                                {
                                    InvoiceId = 1,
                                    Amount = 1500.00m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    InvoiceId = 2,
                                    Amount = 250.50m,
                                    Currency = "EUR"
                                },
                                new
                                {
                                    InvoiceId = 3,
                                    Amount = 3000.00m,
                                    Currency = "GBP"
                                },
                                new
                                {
                                    InvoiceId = 4,
                                    Amount = 450.00m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    InvoiceId = 5,
                                    Amount = 1200.00m,
                                    Currency = "CAD"
                                },
                                new
                                {
                                    InvoiceId = 6,
                                    Amount = 85.00m,
                                    Currency = "USD"
                                });
                        });

                    b.Navigation("MoneyAmount")
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("EfcCodeFirst.Entites.Project", b =>
                {
                    b.HasOne("EfcCodeFirst.Entites.Client", "Client")
                        .WithMany("Projects")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");
                });

            modelBuilder.Entity("EfcCodeFirst.Entites.ProjectFreelancer", b =>
                {
                    b.HasOne("EfcCodeFirst.Entites.Freelancer", "Freelancer")
                        .WithMany("ProjectFreelancers")
                        .HasForeignKey("FreelancerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EfcCodeFirst.Entites.Project", "Project")
                        .WithMany("ProjectFreelancers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Freelancer");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("EfcCodeFirst.Entites.Client", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("EfcCodeFirst.Entites.Freelancer", b =>
                {
                    b.Navigation("FreelancerSkills");

                    b.Navigation("ProjectFreelancers");
                });

            modelBuilder.Entity("EfcCodeFirst.Entites.Project", b =>
                {
                    b.Navigation("Contract")
                        .IsRequired();

                    b.Navigation("Invoices");

                    b.Navigation("ProjectFreelancers");
                });

            modelBuilder.Entity("EfcCodeFirst.Entites.Skill", b =>
                {
                    b.Navigation("FreelancerSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
